### ISSUE TITLE
Fixes for dashboard 

### ISSUE THREAD

**Issue by wjurkowlaniec** [safe-scan-ai/cancer-ai#100]
After doing #99 and merging my PR, following items for dashboard. Link to repo - https://github.com/safe-scan-ai/competition-dashboard

- [ ] fetch config from `competition_config.json` and whitelist which keys should be displayed on the dashboard
- [ ] Competition summary - remove two first columns, "Run at" as first column, "tested entries"
- [x] both tables should have the same style and display top 10 entries with paging and (optional) frontend-only search for miner_hotkey
- [ ] Models evaluation - all columns from WANDB entry, + hugging face link. Also "Run at" as first column,score as last, and remove ID/Username/First column with number. Recall is 0
- [x] when I click melanoma-1, it raises error
- [x] summary should work

**Comment by notbulubula** [comment]
All changes are being updated here https://github.com/safe-scan-ai/competition-dashboard/pull/2
