### ISSUE TITLE
Research degradation rewards

### ISSUE THREAD

**Issue by wjurkowlaniec** [safe-scan-ai/cancer-ai#12]
when we have multiple competitions,
- reduce gradually incentive for best miner when model isn't improving or just by small amount

for example, we have 3 competitions, for 3 different models, each receives 33% of miner emissions
when improvement is less than 1% during a week, reduce by 10%

figure out the numbers

**Comment by LEMSTUDI0** [comment]
https://docs.google.com/spreadsheets/d/1GVHXBTZRGbMMbyjestGxKpmFY1jvsQiJ19TJHmVUmto/edit?gid=0#gid=0

emisja cala minus konkursy z decayem*procent spadku i pozostała ilosc procentow emisji dzielona na ilosc konkursow bez deceya upraszczajac
