### ISSUE TITLE
Data sending to WANDB

### ISSUE THREAD

**Issue by wjurkowlaniec** [safe-scan-ai/cancer-ai#7]
Run 
 - hotkey
 - tested entries
 - accuracy 
 - precision / recall (TODO code for computing confusion matrix) - dodatkowa metryka, nie brana pod uwagę do rankingu
 - model test run time 
 - ROC curve 

Example code for sending data

**Comment by notbulubula** [comment]
All done, except for hotkey - what format is it and from where should it be retrieved?
