### ISSUE TITLE
Most popular ML models formats

### ISSUE THREAD

**Issue by wjurkowlaniec** [safe-scan-ai/cancer-ai#8]
- reseracher which are  most common 
- provide requirements and code for running depending on the format 

 folder `cancer_ai/ml`

**Comment by notbulubula** [comment]
I porvided the code for scikitlearn, tensorflow nad pytorch. But due to size off all required packages, for now on the brach there is only option of using scikit.

**Comment by wjurkowlaniec** [comment]
we agreed to use only ONNX, it simplifies model distribution
